server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: "client-1"

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

topic:
  create-client: create.client
  create-client-scheduler: create.client.scheduler