server:
  port: 8081

topic:
  create-client: create.client
  create-client-scheduler: create.client.scheduler

scheduler:
  client-creation-period: 30000

spring:
  kafka:
    bootstrap-servers: localhost:29092